version: "3"
services:
  starknet-goerli:
    image: eqlabs/pathfinder:latest
    environment:
      - RUST_LOG=info
      - PATHFINDER_ETHEREUM_API_URL=${PATHFINDER_ETHEREUM_API_URL_GOERLI}
      - PATHFINDER_HTTP_RPC_ADDRESS=0.0.0.0:9545
    volumes:
      - goerli-data:/usr/share/pathfinder/data
    ports:
      - 9545:9545
  starknet-mainnet:
    image: eqlabs/pathfinder:latest
    environment:
      - RUST_LOG=info
      - PATHFINDER_ETHEREUM_API_URL=${PATHFINDER_ETHEREUM_API_URL_MAINNET}
      - PATHFINDER_HTTP_RPC_ADDRESS=0.0.0.0:9546
    volumes:
      - mainnet-data:/usr/share/pathfinder/data
    ports:
      - 9546:9546
volumes:
  goerli-data:
    driver_opts:
      uid: 0
      gid: 0
  mainnet-data:
    driver_opts:
      uid: 0
      gid: 0
