version: "3"
services:
  starknet-goerli:
    image: eqlabs/pathfinder:latest
    environment:
      - RUST_LOG=info
      - PATHFINDER_ETHEREUM_API_URL=${PATHFINDER_ETHEREUM_API_URL_GOERLI}
      - PATHFINDER_HTTP_RPC_ADDRESS=0.0.0.0:9545
    volumes:
      - goerli-data:/usr/share/pathfinder/data
    ports:
      - 9545:9545
    entrypoint: ["/usr/bin/tini", "--"]
    command:
      - /bin/bash
      - -c
      - |
        curl https://pathfinder-starknet-node-backup.s3.eu-west-3.amazonaws.com/goerli/goerli.sqlite --output /usr/share/pathfinder/data/goerli.sqlite
        pathfinder

  starknet-mainnet:
    image: eqlabs/pathfinder:latest
    environment:
      - RUST_LOG=info
      - PATHFINDER_ETHEREUM_API_URL=${PATHFINDER_ETHEREUM_API_URL_MAINNET}
      - PATHFINDER_HTTP_RPC_ADDRESS=0.0.0.0:9546
    volumes:
      - mainnet-data:/usr/share/pathfinder/data
    ports:
      - 9546:9546
    entrypoint: ["/usr/bin/tini", "--"]
    command:
      - /bin/bash
      - -c
      - |
        curl https://pathfinder-starknet-node-backup.s3.eu-west-3.amazonaws.com/mainnet/mainnet.sqlite --output /usr/share/pathfinder/data/mainnet.sqlite
        pathfinder

volumes:
  goerli-data:
  mainnet-data:
