{
 "title": "Pathfinder",
 "tags": [
  "pathfinder",
  "starknet"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "network", "label": "Network", "query": "mainnet, testnet-sepolia" }
  ]
 },
 "panels": [
  {
   "title": "Sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sync status",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "current_block{network=\"$network\"}",
       "legendFormat": "{{__name__}}"
      },
      {
       "expr": "highest_block{network=\"$network\"}",
       "legendFormat": "{{__name__}}"
      }
     ]
    },
    {
     "title": "Sync backlog",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 9, "y": 1 },
     "targets": [
      {
       "expr": "highest_block{network=\"$network\"} - current_block{network=\"$network\"}",
       "legendFormat": "Sync backlog"
      }
     ]
    },
    {
     "title": "Block synced / second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "rate(current_block{network=\"$network\"}[$__rate_interval])",
       "legendFormat": "{{network}}"
      }
     ]
    },
    {
     "title": "Block processing 95th percentile",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 9, "y": 10 },
     "targets": [
      {
       "expr": "block_processing_duration_seconds{network=\"$network\", quantile=\"0.95\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Block latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "block_latency{network=\"$network\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Feeder gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gateway requests failed / second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "rate(gateway_requests_failed_total{network=\"$network\"}[$__rate_interval])",
       "legendFormat": "{{method}} {{reason}}"
      }
     ]
    },
    {
     "title": "Gateway requests / second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 9, "y": 2 },
     "targets": [
      {
       "expr": "rate(gateway_requests_total{network=\"$network\"}[$__rate_interval])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Gateway request 95th percentile",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 18, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "gateway_request_duration_seconds{network=\"$network\", quantile=\"0.95\"} != 0",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JSON-RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC method call 95th percentile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "rpc_method_calls_duration_milliseconds{network=\"$network\", quantile=\"0.95\"}",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "RPC request rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "rate(rpc_method_calls_total{network=\"$network\"}[$__rate_interval])",
       "legendFormat": "{{method}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage - Trie nodes removed / second",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 802 },
     "targets": [
      {
       "expr": "rate(pathfinder_storage_trie_nodes_deleted_total{network=\"$network\"}[$__rate_interval])",
       "legendFormat": "{{table}}"
      }
     ]
    },
    {
     "title": "Storage - Trie nodes added / second",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 9, "y": 802 },
     "targets": [
      {
       "expr": "rate(pathfinder_storage_trie_nodes_added_total{network=\"$network\"}[$__rate_interval])",
       "legendFormat": "{{table}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Native Execution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Native class cache",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 803 },
     "targets": [
      {
       "expr": "rate(native_class_cache_hit_total{network=\"$network\"}[$__rate_interval])",
       "legendFormat": "Cache hit"
      },
      {
       "expr": "rate(native_class_cache_miss_total{network=\"$network\"}[$__rate_interval])",
       "legendFormat": "Cache miss"
      },
      {
       "expr": "rate(native_class_cache_miss_compilation_pending_total{network=\"$network\"}[$__rate_interval])",
       "legendFormat": "Cache miss (compilation pending)"
      }
     ]
    },
    {
     "title": "Native class compiler",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 9, "y": 803 },
     "targets": [
      {
       "expr": "native_class_compiled_total{network=\"$network\"}",
       "legendFormat": "Compiled"
      },
      {
       "expr": "native_class_compilation_errors_total{network=\"$network\"}",
       "legendFormat": "Errors"
      }
     ]
    },
    {
     "title": "Native compilation queue size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 812 },
     "targets": [
      {
       "expr": "native_class_compilation_queued_total{network=\"$network\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Native compilation duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 9, "y": 812 },
     "targets": [
      {
       "expr": "native_class_compilation_duration_seconds{network=\"$network\"}",
       "legendFormat": "Compilation time quantile {{quantile}}"
      }
     ]
    },
    {
     "title": "Native compilation per-class object size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 821 },
     "targets": [
      {
       "expr": "native_class_compilation_object_size_bytes{network=\"$network\"}",
       "legendFormat": "Object size quantile {{quantile}}"
      }
     ]
    },
    {
     "title": "Native compiled classes total size",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 9, "x": 9, "y": 821 },
     "targets": [
      {
       "expr": "native_class_compilation_object_size_bytes_sum{network=\"$network\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}