name: Free disk space
description: Remove unused pre-installed software to free up disk space

runs:
  using: composite
  steps:
    - name: Free disk space
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/share/swift
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo docker image prune --all --force
