[package]
name = "stark_hash"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "stark_hash"
path = "src/lib.rs"

[build-dependencies]
stark_curve = { path = "../stark_curve" }

[dependencies]
# paritys scale codec locks us here
#bitvec = "0.20.4"
bitvec = "1.0.1"
rand_core = "0.6.3"
serde = "1.0.134"
stark_curve = { path = "../stark_curve" }

[dev-dependencies]
assert_matches = "1.5.0"
criterion = "0.3"
hex = "0.4.3"
pretty_assertions = "1.0.0"
rand = "0.8"
serde_json = "1.0.75"

[[bench]]
name = "stark_hash"
harness = false
